name: Atualizar placares Copa

on:
  schedule:
    - cron: "*/10 * * * *"  # a cada 10 minutos

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar script
        run: python update_scores.py

      - name: Commit alterações
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add games.json
          git commit -m "Atualizando scores automaticamente" || echo "Sem mudanças"
          git push
